### ISSUE TITLE
Can we dual boot it with windows 

### ISSUE THREAD

**Issue by darsaliq00** [chilledHamza/Hackintosh_Legion_Y7000_2018#11]
I flashes windows after using MacOS but MacOS isn't booting now. Its only booting with usb drive

**Comment by chilledHamza** [comment]
> I flashes windows after using MacOS but MacOS isn't booting now. Its only booting with usb drive

Dual-Boot is possible with OpenCore, I'm currently using triple boot (Windows, macOS, Arch Linux) on my XPS 17. Set `LauncherOption` -> `Full` in config.plist to avoid boot configuration override by `Windows Boot Manager`, you can check [Dortania | Using LauncherOption](https://dortania.github.io/OpenCore-Post-Install/multiboot/bootstrap.html#prerequisites) for details.
