### ISSUE TITLE
What I need to do to make it work with Y540

### ISSUE THREAD

**Issue by MiSalocin** [chilledHamza/Hackintosh_Legion_Y7000_2018#2]
I've tried to use this one with a y540 notebook, previously I was using the xiaoMGitHub clover EFI and I'v
e tried substitute with this one but didn't work and I've received this error, any idea what I could do to fix it?
![image](https://user-images.githubusercontent.com/61383781/104678721-ce552080-56ca-11eb-9eca-ffceae9fbfb6.png)

**Comment by chilledHamza** [comment]
Seems like the DVMT pre-allocated memory panic.

Either set DVMT pre-allocated memory to 64M in BIOS, or use patch in DeviceProperties

To make my EFI work, you have to apply all the specified BIOS settings (or use alternative patches).
