### ISSUE TITLE
Wi-Fi Not working

### ISSUE THREAD

**Issue by ichigo86150** [chilledHamza/Hackintosh_Legion_Y7000_2018#9]
Hey,

Fun to see, but for me Bluetooth is working, but my wi-fi card isn't, maybe i've failed some steps? I can't activate it it's greyed out.
Config:
- Lenovo Legion Y530-15ICH
- GTX 1060 (disabled in Monterey)
- i5-8300h (4c/8t)
- 16GB DDR4 2666Mhz (2x8)

Thanks by advance!

**Comment by ichigo86150** [comment]
Fixed by using itlwm -> https://github.com/OpenIntelWireless/itlwm and Heliport
This is not native Wi-Fi but i'll check later for AirPort. :)

**Comment by chilledHamza** [comment]
> Fixed by using itlwm -> https://github.com/OpenIntelWireless/itlwm and Heliport

Use AirportItlwm for Native Wi-Fi selection and switching (won't need Heliport app), but you cannot have both kexts enabled at same time so don't forget to disable/remove Itlwm before trying AirportItlwm

> This is not native Wi-Fi but i'll check later for AirPort. :)

Just replace the kext and it should work, also remove Broadcom related kernel extensions as you have intel wireless chipset instead.

Intel wireless works fine, except AirDrop (which is partially broken on non-apple broadcom chipsets anyway, as of macOS Monterey)

check Itlwm/IntelBluetooth documentation for details
